# Generated by Django 4.2.5 on 2023-09-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.TextField()),
                ("Authors", models.JSONField(default=list)),
                ("Abstract", models.CharField(max_length=50000)),
                ("Pdf", models.URLField()),
                ("PaperLink", models.URLField()),
                ("Tags", models.JSONField(default=list)),
            ],
        ),
    ]
